#!/usr/bin/env bash
set -Eeuo pipefail

# Function to converge mkinitcpio configuration and generate UKIs
# This script configures mkinitcpio to use systemd hooks, generates UKIs, and signs them with sbctl.
converge_mkinitcpio() {
  local cfg_mkinit="config/mkinitcpio.yaml"
  local cfg_boot="config/boot.yaml"
  local conf_file="/mnt/etc/mkinitcpio.conf"

  echo ">>> Configuring mkinitcpio..."

  # Read hooks and modules from yaml
  local hooks
  hooks=$(yq -r '.hooks | join(" ")' "$cfg_mkinit")
  local modules="" # Keeping modules empty as per Source B strategy

  # Write mkinitcpio.conf
  cat <<EOF > "$conf_file"
# Generated by arch_os_as_code
MODULES=($modules)
BINARIES=()
FILES=()
HOOKS=($hooks)
EOF

  echo "    Written $conf_file"

  # Configure Presets for UKI
  mkdir -p /mnt/efi/EFI/Linux

  # Read kernels from config/boot.yaml
  # We extract the package names (e.g., linux, linux-hardened) which usually match the preset names
  # But wait, preset names match the package name usually.
  # Let's assume the 'package' field in boot.yaml corresponds to the preset name base.
  mapfile -t kernels < <(yq -r '.kernels[].package' "$cfg_boot")

  for kernel in "${kernels[@]}"; do
      local preset="/mnt/etc/mkinitcpio.d/${kernel}.preset"
      echo "    Configuring preset for $kernel..."

      # Determine paths
      local kver="/boot/vmlinuz-${kernel}"
      local uki_default="/efi/EFI/Linux/arch-${kernel}.efi"

      # Write preset file (No fallback)
      cat <<EOF > "$preset"
# mkinitcpio preset file for $kernel (UKI)
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="$kver"
ALL_microcode=(/boot/*-ucode.img)

PRESETS=('default')

default_uki="$uki_default"
default_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp"
EOF
  done

  # Write kernel command line
  # We use Discoverable Partitions, so we don't need root=... or cryptdevice=...
  # Removed hardening parameters (apparmor, firejail, etc.) as requested.
  echo ">>> Writing /mnt/etc/kernel/cmdline..."
  local cmdline="rw quiet"
  echo "$cmdline" > /mnt/etc/kernel/cmdline

  echo ">>> Generating UKIs..."
  arch-chroot /mnt mkinitcpio -P

  echo ">>> Signing UKIs with sbctl..."
  # Ensure sbctl is initialized
  if ! arch-chroot /mnt sbctl status | grep -q "Setup Mode"; then
      if [ ! -f /mnt/usr/share/secureboot/keys/PK/PK.key ]; then
          echo "    Creating secure boot keys..."
          arch-chroot /mnt sbctl create-keys
      fi
  fi

  # Enroll keys with Microsoft flag
  # This is best effort; requires Setup Mode.
  echo "    Enrolling keys (including Microsoft)..."
  # We use || true because if not in Setup Mode, this will fail, but we don't want to abort the script.
  arch-chroot /mnt sbctl enroll-keys -m || echo "    Warning: Failed to enroll keys. Ensure Secure Boot is in Setup Mode."

  # Sign the UKIs
  for kernel in "${kernels[@]}"; do
      local uki_default="/efi/EFI/Linux/arch-${kernel}.efi"

      if [ -f "/mnt$uki_default" ]; then
          echo "    Signing $uki_default..."
          arch-chroot /mnt sbctl sign -s "$uki_default"
      fi
  done
}
